import type { Metadata } from 'next';
import { Inter, Bebas_Neue } from 'next/font/google';
import './globals.css';

const bebas = Bebas_Neue({
  subsets: ['latin'],
  weight: '400', // Bebas Neue has only one weight
  variable: '--font-bebas',
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Investify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={bebas.variable}>
      <body className={inter.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
